---
title: "生物統計学レポート"
author: "髙良力樹"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    highlight: tango
    toc: true
    smart: false
#  pdf_document:
#    latex_engine: lualatex
#    toc: false
documentclass: bxjsarticle
classoption: lualatex
mainfont: ipaexg.ttf
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, ggtext, lattice)
```

## 環境要件

```{r}
sessionInfo()
```

## 1.オオムギ収量の箱ひげ図

```{r pressure, echo=FALSE}
ggplot(barley, aes(x= variety, y=yield))+
  theme_bw()+
  geom_boxplot()+
  geom_jitter(aes(colour=year),width = 0.2)+
  scale_colour_manual(values = c("#D59B0A", "#DECA98"))+
  labs(
    title = "yield graph",
    x = "variety",
    y = "yield [bu/ac]"
  )+
  theme(plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
        axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        plot.caption = element_text(size = 8)
  )+
  scale_x_discrete(guide = guide_axis(n.dodge = 2))

```

